### ISSUE TITLE
blog webpack学习之路

### ISSUE THREAD

**Issue by SirM2z** [wangning0/Autumn_Ning_Blog#1]
blog文章中 ：webpack学习之路    模块系统的几种类型    <script> 标签类型  缺点里第一条语句不完整

**Comment by dctxf** [comment]
挺好的，加油

**Comment by rdmclin2** [comment]
你好，这篇文章npm install的时候忘记`file-loader`了，另外对于图片，虽然转了，但是并没有在index.html中引用到生成的图片,也许需要说明一下。

**Comment by wangyoukun** [comment]
index.js 这个文件里面的内容是啥啊？
