### ISSUE TITLE
bundle名字错误&缺少file-loader

### ISSUE THREAD

**Issue by zzlune** [wangning0/Autumn_Ning_Blog#10]
指出2个小问题：
1、index.html中<script>加载的js文件名称错误：bundlle.js—>bundle.js
2、

$ npm install style-loader css-loader image-webpack-loader webpack --save-dev

缺少一个file-loader:

$ npm install file-loader style-loader css-loader image-webpack-loader webpack --save-dev

**Comment by wangning0** [comment]
谢谢指出
